---
output: github_document
---

<!-- README.md is generated from README.Rmd. Please edit that file -->

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>",
  fig.path = "man/figures/README-",
  out.width = "100%"
)
```

# sep

The goal of `sep` is to help collaborators and interested users to create graphics as used in the Swiss Environmental Panel Reports.

## Installation

You can install a development version of `sep` from [GitHub](https://github.com/) with:

```{r, message=FALSE}
# install.packages("devtools")
devtools::install_github("bonschorno/sep")
```

```{r}
library(sep)
library(tidyverse)
```


## Example

First, replace the default theme of ggplot2 with `theme_sep.`

```{r}
#theme_set(theme_sep())
```


```{r example, fig.retina=3}
#create a simple barplot with manually adjusted with of bars
simple_barplot(df = mtcars, var = gear, title = "Gears", width = 0.3) 
```

```{r}
# creating a simple crosstable

crosstable(vars = c("gear", "am"), df = mtcars)
```

